#!/usr/bin/env python3
"""Colored ASCII banner of GMB Foundry Creature Converter (by Geek Metaverse Bots).

    python banner.py            show it
    python banner.py --plain    without colors

Shown automatically once — the first time a script runs in a real terminal.
Respects NO_COLOR. Generated by assets/src/make_banner.py; edit that, not this.
"""
import os
import sys
from pathlib import Path

LOGO = [
    " GEEK#METAVERS  E#BOTS#GEEK#M ",
    "ETAVERSE#BOTS#  GEEK#METAVERSE",
    "#BOTS#G         EEK#ME        ",
    "TAVERS  E#BOTS  #GEEK#METAV   ",
    "ERSE#B  OTS#GE  EK#METAVERS   ",
    "E#BOTS   #GEEK  #METAVERSE#BOT",
    "S#GEEK#METAVER  SE#BOTS#GEEK# ",
    "METAVERSE#BOT                 ",
    "                S#GEEK   #META",
    " VERSE#BOTS#GE  EK#MET AVERSE#",
    "BOTS#GEEK#      METAVERSE#BO  ",
    "TS#GEEK#METAV   ERSE#BOTS#G   ",
    "EEK#METAVERS    E#BOTS#GEEK#  ",
    "METAVERSE#BO    TS#GEEK#METAV ",
    "ERSE#BOTS#GEEK  #METAV  ERSE#B",
    " OTS#GEEK#META  VERSE#   BOTS "
]
TITLE = [
    "      {}[]{}      [            ]     { }[]{      ",
    "   }[]{}[]{}[]    {}[]{    }[]{}[   ]{}[]{}[]{   ",
    "  }[]{            }[]{}[   ]{}[]{   }[]    {}[]  ",
    "  {}[             ]{} []  {} []{}   []{}[]{}[]   ",
    "  {}[    ]{}[]    {}[  ]{}[] {}[]   {}[]  {}[]   ",
    "  {}[]     {}[    ]{}   []{  }[]{   }[]     {}[  ",
    "   ]{}[]{}[]{}    []{        }[]{   }[]{}[]{}[]  ",
    "      {}[]{}      []          {}     [ ]{}[      "
]
TEXT = [('head', 'FOUNDRY · CREATURE · CONVERTER'), ('norm', 'статблок ➜ JSON для Foundry VTT'), ('blank', ''), ('dim', 'by Geek Metaverse Bots'), ('norm', '🌐 geek-metaverse-bots.ru'), ('norm', '🎲 t.me/GeekDungeonMasterBot')]
GAP = 3

# gradients (r, g, b) stops
EMBER = [(255, 224, 102), (255, 122, 61), (255, 46, 99), (168, 85, 247)]
ARCANE = [(34, 211, 238), (168, 85, 247), (255, 46, 99)]


def _lerp(stops, t):
    t = max(0.0, min(1.0, t)) * (len(stops) - 1)
    i = min(int(t), len(stops) - 2)
    f = t - i
    a, b = stops[i], stops[i + 1]
    return tuple(round(a[k] + (b[k] - a[k]) * f) for k in range(3))


def _mode():
    if os.environ.get("NO_COLOR") or "--plain" in sys.argv:
        return "plain"
    ct = os.environ.get("COLORTERM", "").lower()
    if "truecolor" in ct or "24bit" in ct or os.environ.get("WT_SESSION") or os.environ.get("TERM_PROGRAM") in ("vscode", "iTerm.app", "WezTerm"):
        return "true"
    return "256"


def _fg(rgb, mode):
    if mode == "plain":
        return ""
    r, g, b = rgb
    if mode == "true":
        return f"\033[38;2;{r};{g};{b}m"
    idx = 16 + 36 * round(r / 255 * 5) + 6 * round(g / 255 * 5) + round(b / 255 * 5)
    return f"\033[38;5;{idx}m"


def render(mode=None):
    mode = mode or _mode()
    reset = "" if mode == "plain" else "\033[0m"
    bold = "" if mode == "plain" else "\033[1m"
    dim = "" if mode == "plain" else "\033[2m"
    lw = max(len(r) for r in LOGO)
    right = [("title", r) for r in TITLE] + [("blank", "")] + [("text", t) for t in TEXT]
    pad = max(0, (len(LOGO) - len(right)) // 2)
    right = [("blank", "")] * pad + right
    tw = max(len(r) for r in TITLE)
    lines = []
    for i in range(max(len(LOGO), len(right))):
        out = ""
        row = LOGO[i] if i < len(LOGO) else ""
        for j, ch in enumerate(row.ljust(lw)):
            out += ch if ch == " " else _fg(_lerp(EMBER, (i / max(1, len(LOGO) - 1)) * 0.75 + (j / lw) * 0.25), mode) + ch
        out += reset + " " * GAP
        kind, txt = right[i] if i < len(right) else ("blank", "")
        if kind == "title":
            for j, ch in enumerate(txt):
                out += ch if ch == " " else _fg(_lerp(ARCANE, j / max(1, tw - 1)), mode) + ch
            out += reset
        elif kind == "text":
            style, s = txt
            if style == "head":
                out += bold
                for j, ch in enumerate(s):
                    out += _fg(_lerp(EMBER, j / max(1, len(s) - 1)), mode) + ch
            elif style == "dim":
                out += dim + s
            else:
                out += s
            out += reset
        lines.append(out.rstrip())
    return "\n".join(lines) + "\n"


def _enable_windows_ansi():
    if os.name == "nt":
        os.system("")  # turns on VT processing in the Windows console


def show(stream=sys.stdout):
    _enable_windows_ansi()
    try:
        stream.write(render())
    except UnicodeEncodeError:
        stream.write(render("plain").encode("ascii", "replace").decode())
    stream.flush()


def _marker():
    base = os.environ.get("APPDATA") if os.name == "nt" else os.environ.get("XDG_CONFIG_HOME", str(Path.home() / ".config"))
    return Path(base or Path.home()) / "gmb-foundry-creature-converter" / "welcome-shown"


def maybe_show_first_run(stream=sys.stderr):
    """Show the banner once, only to a human at a terminal (never inside agents/pipes)."""
    try:
        if not stream.isatty() or os.environ.get("CI"):
            return
        m = _marker()
        if m.exists():
            return
        show(stream)
        m.parent.mkdir(parents=True, exist_ok=True)
        m.write_text("1", encoding="utf-8")
    except Exception:
        pass


if __name__ == "__main__":
    show()
